### Numpy

In [1]:
import numpy as np

In [2]:
x=[[1,2],[3,4]]
tot=0
for i in x:
    tot+=sum(i)
print(tot)        

10


In [3]:
nx=np.array(x)

In [4]:
nx.sum()

10

In [5]:
print(nx.min())
print(nx.max())
print(nx.mean())
print(nx.std())
print(nx.var())

1
4
2.5
1.118033988749895
1.25


In [6]:
type(nx)

numpy.ndarray

In [7]:
print(nx.shape) #shape of matrix
print(nx.size)  #total elements
print(nx.dtype) #type of elements

(2, 2)
4
int32


In [8]:
d3array=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(d3array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Functions to create matrix
- arange: create a range of numbers
- linspace: create a matrix of specified number of elements
- ones: create a matrix of ones
- zeroes: create a matrix of zero
- random.randint: create a matrix of random integer
- random.rand: create a matrix of random float
- diag: create a matrix with diagonal elements 

In [9]:
a=np.arange(1,50)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]


In [10]:
np.arange(1,5,.2)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8])

In [11]:
np.linspace(1,2,10) #this means keep 10 values between the range 1 to 2

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [12]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros((4,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [16]:
np.random.randint(1,100,10) #this mean a array of 10 elemntes with randome value between 1 to 100

array([53, 98,  9, 73, 61,  5, 11, 67, 21, 57])

In [17]:
print(np.random.randint(-5,5,(5,5)))

[[ 2 -2  2  2  2]
 [-1 -3  4  2 -2]
 [ 1  1 -4  2 -5]
 [-4  1 -5 -1  3]
 [ 0 -1 -2  4 -1]]


In [18]:
np.random.rand(5) #5 is the number of values

array([0.39594903, 0.74779104, 0.50022202, 0.44157735, 0.76840825])

In [19]:
np.random.rand(5,5) #5*5 matrix

array([[0.25162832, 0.61006501, 0.87773881, 0.98555122, 0.54733599],
       [0.3334359 , 0.3508764 , 0.45226558, 0.89800849, 0.4236747 ],
       [0.15472246, 0.16975849, 0.04179317, 0.51323725, 0.66628439],
       [0.64750649, 0.27872388, 0.46772775, 0.95694284, 0.17233399],
       [0.88523   , 0.47410991, 0.13150277, 0.36387766, 0.204009  ]])

In [20]:
np.set_printoptions(precision=2)  #decide the number of decimal values
np.random.rand(5,5) 

array([[0.2 , 0.17, 0.49, 0.44, 0.29],
       [0.24, 0.49, 0.06, 0.71, 0.99],
       [0.71, 0.9 , 0.37, 1.  , 0.34],
       [0.14, 0.74, 0.61, 0.21, 0.96],
       [0.4 , 0.76, 0.87, 0.18, 0.47]])

In [21]:
x=[1,2,3,4,5]
np.diag(x)  #diagonal matrix

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [22]:
y=[[1,2,3],[4,5,6],[7,8,9]]
np.diag(y)

array([1, 5, 9])

In [23]:
#reshape
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [24]:
x=np.linspace(1,250,25).reshape(5,5)

In [25]:
x.flatten()

array([  1.  ,  11.38,  21.75,  32.12,  42.5 ,  52.88,  63.25,  73.62,
        84.  ,  94.38, 104.75, 115.12, 125.5 , 135.88, 146.25, 156.62,
       167.  , 177.38, 187.75, 198.12, 208.5 , 218.88, 229.25, 239.62,
       250.  ])

In [26]:
y=np.arange(1,26).reshape(5,5)
print(y)
print(y.transpose()) # or we can do y.T where T stands for transpose

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]
 [ 5 10 15 20 25]]


### Maths


In [27]:
a=np.random.randint(1,10,(3,3))
b=np.random.randint(1,10,(3,3))
print(a)
print(b)

[[1 3 1]
 [4 3 8]
 [1 3 4]]
[[9 3 4]
 [8 9 4]
 [5 1 1]]


In [28]:
a+b

array([[10,  6,  5],
       [12, 12, 12],
       [ 6,  4,  5]])

In [29]:
a-b

array([[-8,  0, -3],
       [-4, -6,  4],
       [-4,  2,  3]])

In [30]:
a*b  #multiply values

array([[ 9,  9,  4],
       [32, 27, 32],
       [ 5,  3,  4]])

In [31]:
a/b

array([[0.11, 1.  , 0.25],
       [0.5 , 0.33, 2.  ],
       [0.2 , 3.  , 4.  ]])

In [32]:
a//b

array([[0, 1, 0],
       [0, 0, 2],
       [0, 3, 4]])

In [33]:
a.dot(b) #dot product matrix multiplication

array([[ 38,  31,  17],
       [100,  47,  36],
       [ 53,  34,  20]])

In [34]:
a+10

array([[11, 13, 11],
       [14, 13, 18],
       [11, 13, 14]])

In [35]:
print(a.mean()) #mean of complete matix
print(a.mean(axis=0)) #mean of column axis
print(a.mean(axis=1)) #mean of row axis

3.111111111111111
[2.   3.   4.33]
[1.67 5.   2.67]


In [36]:
print(a.sum()) #sum of complete matix
print(a.sum(axis=0)) #sum of column axis
print(a.sum(axis=1)) #sum of row axis

28
[ 6  9 13]
[ 5 15  8]


In [37]:
print(np.sin(a))  #calculation of sin in a matrix for each value but it is in  randiance
print(np.cos(a))  
print(np.tan(a))  

[[ 0.84  0.14  0.84]
 [-0.76  0.14  0.99]
 [ 0.84  0.14 -0.76]]
[[ 0.54 -0.99  0.54]
 [-0.65 -0.99 -0.15]
 [ 0.54 -0.99 -0.65]]
[[ 1.56 -0.14  1.56]
 [ 1.16 -0.14 -6.8 ]
 [ 1.56 -0.14  1.16]]


In [38]:
print(np.exp(a))  #calculation of exponential value of a
print(np.sqrt(a))
print(np.max(a))
print(np.min(a))

[[2.72e+00 2.01e+01 2.72e+00]
 [5.46e+01 2.01e+01 2.98e+03]
 [2.72e+00 2.01e+01 5.46e+01]]
[[1.   1.73 1.  ]
 [2.   1.73 2.83]
 [1.   1.73 2.  ]]
8
1


In [39]:
print(np.argmax(a)) #index of max value
print(np.argmin(a)) #index of min value

5
0
