### Numpy

In [1]:
import numpy as np

In [9]:
x=[[1,2],[3,4]]
tot=0
for i in x:
    tot+=sum(i)
print(tot)        

10


In [10]:
nx=np.array(x)

In [11]:
nx.sum()

np.int64(10)

In [12]:
print(nx.min())
print(nx.max())
print(nx.mean())
print(nx.std())
print(nx.var())

1
4
2.5
1.118033988749895
1.25


In [13]:
type(nx)

numpy.ndarray

In [16]:
print(nx.shape) #shape of matrix
print(nx.size)  #total elements
print(nx.dtype) #type of elements

(2, 2)
4
int64


In [17]:
d3array=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(d3array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Functions to create matrix
- arange: create a range of numbers
- linspace: create a matrix of specified number of elements
- ones: create a matrix of ones
- zeroes: create a matrix of zero
- random.randint: create a matrix of random integer
- random.rand: create a matrix of random float
- diag: create a matrix with diagonal elements 

In [18]:
a=np.arange(1,50)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]


In [24]:
np.arange(1,5,.2)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8])

In [28]:
np.linspace(1,2,10) #this means keep 10 values between the range 1 to 2

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [29]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [30]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [32]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
np.zeros((4,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [34]:
np.random.randint(1,100,10) #this mean a array of 10 elemntes with randome value between 1 to 100

array([29, 11, 38, 13, 57, 60, 36, 18, 51,  9], dtype=int32)

In [36]:
print(np.random.randint(-5,5,(5,5)))

[[ 3  0  1 -3  1]
 [ 4 -5  0  2  0]
 [ 3  0 -5  2 -5]
 [-4  4 -4  0  4]
 [ 4 -3  2 -4  4]]


In [37]:
np.random.rand(5) #5 is the number of values

array([0.22168685, 0.19115266, 0.19077125, 0.95125639, 0.80769689])

In [40]:
np.random.rand(5,5) #5*5 matrix

array([[0.15284794, 0.08268629, 0.10858691, 0.44936335, 0.62713102],
       [0.53747312, 0.5227686 , 0.02707816, 0.1259013 , 0.91948717],
       [0.77125262, 0.90843106, 0.11465347, 0.53937535, 0.36576301],
       [0.7264959 , 0.73604797, 0.30777699, 0.39337466, 0.93870221],
       [0.77626334, 0.88645074, 0.70172153, 0.29194373, 0.98245022]])

In [42]:
np.set_printoptions(precision=2)  #decide the number of decimal values
np.random.rand(5,5) 

array([[0.32, 0.57, 0.53, 0.11, 0.41],
       [0.93, 0.7 , 0.55, 0.89, 0.61],
       [0.71, 0.96, 0.22, 0.69, 0.5 ],
       [0.08, 0.67, 0.6 , 0.61, 0.46],
       [0.53, 0.81, 0.59, 0.82, 0.87]])

In [44]:
x=[1,2,3,4,5]
np.diag(x)  #diagonal matrix

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [45]:
y=[[1,2,3],[4,5,6],[7,8,9]]
np.diag(y)

array([1, 5, 9])

In [49]:
#reshape
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [53]:
x=np.linspace(1,250,25).reshape(5,5)

In [54]:
x.flatten()

array([  1.  ,  11.38,  21.75,  32.12,  42.5 ,  52.88,  63.25,  73.62,
        84.  ,  94.38, 104.75, 115.12, 125.5 , 135.88, 146.25, 156.62,
       167.  , 177.38, 187.75, 198.12, 208.5 , 218.88, 229.25, 239.62,
       250.  ])

In [57]:
y=np.arange(1,26).reshape(5,5)
print(y)
print(y.transpose()) # or we can do y.T where T stands for transpose

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]
 [ 5 10 15 20 25]]


### Maths


In [58]:
a=np.random.randint(1,10,(3,3))
b=np.random.randint(1,10,(3,3))
print(a)
print(b)

[[3 9 9]
 [8 3 3]
 [9 8 6]]
[[4 7 7]
 [2 6 9]
 [2 3 7]]


In [59]:
a+b

array([[ 7, 16, 16],
       [10,  9, 12],
       [11, 11, 13]], dtype=int32)

In [60]:
a-b

array([[-1,  2,  2],
       [ 6, -3, -6],
       [ 7,  5, -1]], dtype=int32)

In [61]:
a*b  #multiply values

array([[12, 63, 63],
       [16, 18, 27],
       [18, 24, 42]], dtype=int32)

In [62]:
a/b

array([[0.75, 1.29, 1.29],
       [4.  , 0.5 , 0.33],
       [4.5 , 2.67, 0.86]])

In [63]:
a//b

array([[0, 1, 1],
       [4, 0, 0],
       [4, 2, 0]], dtype=int32)

In [65]:
a.dot(b) #dot product matrix multiplication

array([[ 48, 102, 165],
       [ 44,  83, 104],
       [ 64, 129, 177]], dtype=int32)

In [66]:
a+10

array([[13, 19, 19],
       [18, 13, 13],
       [19, 18, 16]], dtype=int32)

In [69]:
print(a.mean()) #mean of complete matix
print(a.mean(axis=0)) #mean of column axis
print(a.mean(axis=1)) #mean of row axis

6.444444444444445
[6.67 6.67 6.  ]
[7.   4.67 7.67]


In [68]:
print(a.sum()) #sum of complete matix
print(a.sum(axis=0)) #sum of column axis
print(a.sum(axis=1)) #sum of row axis

58
[20 20 18]
[21 14 23]


In [71]:
print(np.sin(a))  #calculation of sin in a matrix for each value but it is in  randiance
print(np.cos(a))  
print(np.tan(a))  

[[ 0.14  0.41  0.41]
 [ 0.99  0.14  0.14]
 [ 0.41  0.99 -0.28]]
[[-0.99 -0.91 -0.91]
 [-0.15 -0.99 -0.99]
 [-0.91 -0.15  0.96]]
[[-0.14 -0.45 -0.45]
 [-6.8  -0.14 -0.14]
 [-0.45 -6.8  -0.29]]


In [72]:
print(np.exp(a))  #calculation of exponential value of a
print(np.sqrt(a))
print(np.max(a))
print(np.min(a))

[[  20.09 8103.08 8103.08]
 [2980.96   20.09   20.09]
 [8103.08 2980.96  403.43]]
[[1.73 3.   3.  ]
 [2.83 1.73 1.73]
 [3.   2.83 2.45]]
9
3


In [74]:
print(np.argmax(a)) #index of max value
print(np.argmin(a)) #index of min value

1
0
