In [1]:
import numpy as np

### Slicing
- 1D -[start,stop,step]
- 2D -[row_start:row_stop:row_step , col_start:col_stop:col_sep]

In [2]:
x=np.arange(1,11)
print(x[:5])
print(x[-5:])

[1 2 3 4 5]
[ 6  7  8  9 10]


In [5]:
x=np.linspace(1,100,25).reshape(5,5).astype(int)
print(x)
print(x[0])  #row index 0
print(x[-1]) # last row
print(x[2])  #row index 2
print(x[:3]) #row index 0 to 2
print(x[-2:]) #last two rows

[[  1   5   9  13  17]
 [ 21  25  29  34  38]
 [ 42  46  50  54  58]
 [ 62  67  71  75  79]
 [ 83  87  91  95 100]]
[ 1  5  9 13 17]
[ 83  87  91  95 100]
[42 46 50 54 58]
[[ 1  5  9 13 17]
 [21 25 29 34 38]
 [42 46 50 54 58]]
[[ 62  67  71  75  79]
 [ 83  87  91  95 100]]


In [11]:
print(x[:,0])  #column index 0
print(x[:,1])  # last column 
print(x[:,1:3]) #selected rows
print(x[1:4,0:3]) #selcted rows and column
print(x[2:-1,2:])

[ 1 21 42 62 83]
[ 5 25 46 67 87]
[[ 5  9]
 [25 29]
 [46 50]
 [67 71]
 [87 91]]
[[21 25 29]
 [42 46 50]
 [62 67 71]]
[[50 54 58]
 [71 75 79]]


### Filtering

In [14]:
x > 50  #Boolean Filter

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [17]:
x[x>50] #filter values greater than 50 - Broadcasting

array([ 54,  58,  62,  67,  71,  75,  79,  83,  87,  91,  95, 100])

In [20]:
x[(x>40)&(x<80)] #filter the value between 40 and 80

array([42, 46, 50, 54, 58, 62, 67, 71, 75, 79])

In [22]:
x[x % 2 == 0]  #filter even numbers

array([ 34,  38,  42,  46,  50,  54,  58,  62, 100])

Important Libray
- matplotlib - Plotting Library for almost all types of plots
- seaborn - Plotting libray for statistical plots
- ploty - interactive using HTMl
- statsmodels - for support in seaborn
- scipy - for support in seaborn
- nbformat - for support in ploty